[package]
name = "big_enum_set_derive"
version = "0.1.0"
authors = ["Manu Thambi <manu@meshcapital.com>", "Lymia Aluysia <lymia@lymiahugs.com>"]
edition = "2018"

description = "An internal helper crate for big_enum_set."

documentation = "https://docs.rs/big_enum_set_derive/"
repository = "https://github.com/manuthambi/big_enum_set"

license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[features]
nightly = ["proc-macro2/nightly", "darling/diagnostics"]
serde = []

[dependencies]
darling = "0.9.0"
syn = "0.15.18"
quote = "0.6.9"
proc-macro2 = "0.4.21"
bit-set = "0.5.1"
bit-vec = "0.5.1"
